version: '2'

services:
  traefik:
    image: traefik:1.5-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - /etc/ssl/certs/traefik-ca.crt:/traefik-ca.crt
      - /etc/ssl/certs/traefik.crt:/traefik.crt
      - /etc/ssl/private/traefik.key:/traefik.key

networks:
  traefik:
    external: true
