version: '2'

services:
  traefik:
    image: traefik:alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - proxytanet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - /etc/ssl/certs/proxytanet-ca.crt:/proxytanet-ca.crt
      - /etc/ssl/certs/proxytanet.crt:/proxytanet.crt
      - /etc/ssl/private/proxytanet.key:/proxytanet.key

networks:
  proxytanet:
    external: true
